
sudo: false

language: python

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install pybuilder

script:
  - pyb run_unit_tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -s target/reports/coverage
