
sudo: false

language: python

python:
  - "2.7"

before_install:
  - pip install pybuilder

install:
  - pyb -v install_dependencies

script:
  - pyb -v run_unit_tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
