
sudo: false

language: python

python:
  - "2.7"

before_install:
  - pip install pybuilder

install:
 - pyb install_dependencies

script:
  - pyb run_unit_tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -s target/reports/coverage
