
sudo: false

language: python

python:
  - "2.7"

before_install:
  - pip install --upgrade pip
  - pip install codecov pytest-cov

install:
  - pip install .

script:
  - coverage run tests.py

after_success:
  - codecov
